-- Legacy aggregator file
import ModularPhysics.Core.ClassicalFieldTheory.Fields
import ModularPhysics.Core.ClassicalFieldTheory.Action
import ModularPhysics.Core.ClassicalFieldTheory.EulerLagrange
import ModularPhysics.Core.ClassicalFieldTheory.Noether
import ModularPhysics.Core.ClassicalFieldTheory.EnergyMomentum
import ModularPhysics.Core.ClassicalFieldTheory.Scalar
import ModularPhysics.Core.ClassicalFieldTheory.Electromagnetic
import ModularPhysics.Core.ClassicalFieldTheory.YangMills
import ModularPhysics.Core.ClassicalFieldTheory.Solitons
