-- ModularPhysics/Core/ClassicalMechanics.lean
-- Aggregator file for Classical Mechanics module

import ModularPhysics.Core.ClassicalMechanics.PhaseSpace
import ModularPhysics.Core.ClassicalMechanics.Lagrangian
import ModularPhysics.Core.ClassicalMechanics.Hamiltonian
import ModularPhysics.Core.ClassicalMechanics.CanonicalTransforms
import ModularPhysics.Core.ClassicalMechanics.Constraints
import ModularPhysics.Core.ClassicalMechanics.Symmetries
import ModularPhysics.Core.ClassicalMechanics.HamiltonJacobi
import ModularPhysics.Core.ClassicalMechanics.Integrable
import ModularPhysics.Core.ClassicalMechanics.Perturbation
import ModularPhysics.Core.ClassicalMechanics.Chaos
