-- ModularPhysics/Core/GeneralRelativity.lean
-- Aggregator file for General Relativity module

import ModularPhysics.Core.GeneralRelativity.EinsteinEquations
import ModularPhysics.Core.GeneralRelativity.EnergyConditions
import ModularPhysics.Core.GeneralRelativity.Schwarzschild
import ModularPhysics.Core.GeneralRelativity.ReissnerNordstrom
import ModularPhysics.Core.GeneralRelativity.Kerr
import ModularPhysics.Core.GeneralRelativity.BlackHoles
import ModularPhysics.Core.GeneralRelativity.Singularities
import ModularPhysics.Core.GeneralRelativity.GravitationalWaves
import ModularPhysics.Core.GeneralRelativity.Cosmology
